### ISSUE TITLE
update pisa.md

### ISSUE THREAD

**Issue by PisaMJ** [MathsJam/mathsjam-site#113]
Hi,
I'm Agnese, from Pisa MJ. Don't know if it's correct to ask for it here, but I have a request.
Pisa MathsJam this month will be on Thursday 22th. How can I change the date on page?

Thanks, 
Agnese

**Comment by katiesteckles** [comment]
Hi Agnese

You can do this in GitHub - if you add a line to your page's code near the
bottom that looks like this:

changed_dates:

- 2018-02-22


That should change the date for this month. Let me know if you're happy to
do this, or if you would like me to do it for you!


Katie

katiesteckles@gmail.com

katie@mathsjam.com

**Comment by PisaMJ** [comment]
Hi Katie,
thank you.
I added the lines to the page's code and created a pull request. I hope it
is ok.

**Comment by katiesteckles** [comment]
Hi Agnese

That seems to have worked! It's live on the site now.

Thanks!
Katie
katiesteckles@gmail.com
katie@mathsjam.com
