### ISSUE TITLE
Get up to date cities list before we go live

### ISSUE THREAD

**Issue by katiesteckles** [MathsJam/mathsjam-site#12]
I've added a few recently. Need to make sure we've got them all.

**Comment by katiesteckles** [comment]
Cool - I have just been sent another one to add, but they're having their first jam on an odd friday then going regulation thereafter

**Comment by christianp** [comment]
Can you have a go at adding it?

**Comment by katiesteckles** [comment]
That appears to have worked! Will need to note the odd first one though. Have also put it on main MJ site.

**Comment by katiesteckles** [comment]
There's been another few new ones (and I have one more I still actually need to add, in Christchurch NZ which I'll do manually on the old site for now) - but this is enough to get approval from Matt and once I've shown it to him (11th May) we can do one more scrape

**Comment by christianp** [comment]
Up to date as of 2017-05-07
