### ISSUE TITLE
Mathsjam logos in a range of sizes?

### ISSUE THREAD

**Issue by ghira-impavida** [MathsJam/mathsjam-site#123]
The website http://www.brightonbrains.org/ has sprung up from nowhere and lists various regular STEM gatherings in the Brighton area. Various groups have tweeted about it. Right now the mathsjam entry has a thing where a logo could be containing the text:

"We don't have an image for this meetup.

If you have a related image you'd like us to use, submit an issue on GitHub with your name, link to the image and your website / Twitter so we can credit you."

I asked Katie/Christian on slack if this should be some standard logo or maybe the BTN twitter one and Katie said a standard one would be better. Maybe the resources section needs to have some mathsjam logo image files in a range of resolutions for cases like this should they arise again. (MJ branded backgrounds for presentations / letters / etc. seems a bit OTT)

**Comment by katiesteckles** [comment]
Image files in different aspect ratios have now been added to the resources page.
