### ISSUE TITLE
Let's do the 2016 slides on the new site

### ISSUE THREAD

**Issue by katiesteckles** [MathsJam/mathsjam-site#13]
Can't be bothered doing them on the old site then moving them over; I have a folder of files and will upload them once we've got the rest of the site ready.

**Comment by christianp** [comment]
I think we should continue handling slides separately from the rest of the
content, so that this repository is quick to clone when someone wants to
make a change.

**Comment by katiesteckles** [comment]
I've got the folder of them but they all need renaming and PDF versions creating. I will find time to do that asap (but for now it's low on my list).

**Comment by katiesteckles** [comment]
(Links are now all in place, but descriptions are pending)
