### ISSUE TITLE
Some javascript to work out the next mathsjam date

### ISSUE THREAD

**Issue by christianp** [MathsJam/mathsjam-site#15]
At the moment, the "next mathsjam" date is computed at compile time, which means we'd have to rebuild the site each month. 
Just in case that doesn't happen, there should be some javascript which calculates the next date when the page loads, and replaces the displayed date if necessary.

**Comment by katiesteckles** [comment]
Current exceptions: Bombay, which is on the fourth Saturday of each month; Lisbon, which appears to just be doing whatever the fuck it wants; Canberra (doesn't exist yet), whose first meeting is Friday 24th March but will thereafter go to regular dates

**Comment by katiesteckles** [comment]
Canberra NZ, which will meet on the Third Tuesday

**Comment by katiesteckles** [comment]
Update: have added Christchurch to the old site now, and stopped calling it Canberra

**Comment by christianp** [comment]
So I don't forget, the javascript I wrote is at https://codepen.io/christianp/full/yboxGx/.
