### ISSUE TITLE
create a 'how to edit your mathsjam' reference

### ISSUE THREAD

**Issue by christianp** [MathsJam/mathsjam-site#19]
Something like an "edit this page" link on each page. The root of the GitHub repo should have some instructions on what to do.

**Comment by katiesteckles** [comment]
So, anyone can submit a request for an edit but we have to approve them before they go live?

**Comment by christianp** [comment]
yep

**Comment by christianp** [comment]
There's a link at the bottom of each page, and I've just noticed that this repo's README has instructions on how to edit! So I'm closing this now, but in the future we could come up with a friendlier set of instructions somewhere, possibly on the site itself.

**Comment by katiesteckles** [comment]
A couple of edits to make to the readme:
- Not all the fields that you can include are there (Twitter, alternative date rule); do we want to include them all in the sample one, and say if it's not specified it'll be the default value?
- Point out you'll need to be logged in to edit and that they will need to set up an account to do so if they haven't got one already?
- In the resources section, we could include a short bit that's like; "Go to github.com/mathsjam and log in to the mathsjam-site repo (you'll need to create an account); you can then make edits to your MathsJam's details, but we'll check they're ok before we put them live to the site. If you're already looking at a page on the site, clicking 'edit this page' at the bottom will take you directly to the relevant part of the site repo."
