### ISSUE TITLE
Move this repo to a 'mathsjam' organization

### ISSUE THREAD

**Issue by christianp** [MathsJam/mathsjam-site#20]
This repo shouldn't just belong to me. We should create a mathsjam organization and make it the owner.

I haven't done this yet because I want permission from Matt and Colin.

**Comment by katiesteckles** [comment]
I give you permission! waiting for permission from Matt and Colin will take forever. What do we need to do? Happy to pay for a private thingy.

**Comment by christianp** [comment]
Done!
