### ISSUE TITLE
Gathering pages

### ISSUE THREAD

**Issue by katiesteckles** [MathsJam/mathsjam-site#21]
Gatheringinfo.md doesn't appear to be anywhere; let's sack off the testimonials page for now; need to make sure the photos linked to in the about page go to the right place; the Archive is going to be a bit of fun but we can hide it for now while we get the new version up and then wire it in later?

**Comment by katiesteckles** [comment]
Colin's sent through his pages that need redirecting. For now, I'd suggest:

http://www.solipsys.co.uk/MathsJamAbout.html -> gathering/about/
http://www.solipsys.co.uk/MathsJamBlurb.html -> gathering/about/
http://www.solipsys.co.uk/MathsJamExternalLinks.html -> gathering/
http://www.solipsys.co.uk/MathsJamNews.html -> gathering/
http://www.solipsys.co.uk/MathsJamProgram.html -> gathering/gatheringinfo/
http://www.solipsys.co.uk/MathsJamPuzzles.html -> gathering/
http://www.solipsys.co.uk/new/MathsJam.html -> gathering/

And the other two
http://www.solipsys.co.uk/MathsJamBooking.html -> gathering/register/ (this will need more input)
http://www.solipsys.co.uk/MathsJam.html -> gathering/

**Comment by christianp** [comment]
I think we've got all the useful stuff from Colin's pages.

**Comment by katiesteckles** [comment]
I think Colin wants all those URLs to redirect to somewhere in the new site - do those listings above look suitable, and how do we hook all that in?

**Comment by christianp** [comment]
He needs to set up the redirects on his server.

**Comment by katiesteckles** [comment]
Cool - but are we happy with those and should I just send him those lists? What will be the actual URLs of those pages once we go live?

**Comment by katiesteckles** [comment]
Other than that the gatheringinfo.md still isn't in the menu, can we send Colin the list above (so it's mathsjam.com/gathering, etc) for him to set up redirects on his server?

**Comment by katiesteckles** [comment]
Redirects sent to Colin in an email so he can set them up. Further work on Gathering pages to follow when we can have a meetup.
