### ISSUE TITLE
Malmo/Lund has some kind of glyph error

### ISSUE THREAD

**Issue by katiesteckles** [MathsJam/mathsjam-site#24]
It's Malmö with an umlaut. Also Bombay (Mumbai) sits outside its box on the 'Rest of World' page list

**Comment by christianp** [comment]
I've fixed the Bombay problem, but Malmö looks OK to me. I wasn't explicitly setting the character encoding, so I've done that. Does that fix it for you?

**Comment by katiesteckles** [comment]
![screen shot 2017-05-04 at 11 32 51](https://cloud.githubusercontent.com/assets/25103599/25699981/7aa65e68-30bd-11e7-9668-f5639cf01f66.png)

**Comment by christianp** [comment]
what browser, what device, etc. etc.

**Comment by katiesteckles** [comment]
This is Chrome on OSX on a Mac. I got nothing

**Comment by katiesteckles** [comment]
ALSO IT'S WORKING NOW
