### ISSUE TITLE
Resources page

### ISSUE THREAD

**Issue by katiesteckles** [MathsJam/mathsjam-site#25]
I need to properly put this together, but would ideally like it to be behind a password - how easy/possible is this?

**Comment by christianp** [comment]
Easily done - there's a form in mediatemple to password-protect folders. We'd need to handle the files outside this repo so that you can't just get them on GitHub.

**Comment by katiesteckles** [comment]
Things to go in it, for my reference:
- MathsJam postcards, printable sign that says MathsJam
- New MathsJam printable customisable poster, which I'm asking for now from Simon
- Standard blurb text, and facts organisers should know
- Suggested wording for emails to promote Jam, monthly reminder
- Archive of MJ Shout
- Link to Slackipy

**Comment by katiesteckles** [comment]
So, for a poster: it just occurred to me it'd be nice to do one using the new site graphics. Would it be possible to autogenerate them using people's local Jam info and have them be downloadable through the site? I can create an SVG that has named objects we'd just need to edit the text in - I've done similar before here: 
https://github.com/basak/svg-mail-merge
Can it be built into the website?

**Comment by christianp** [comment]
Yes.

**Comment by katiesteckles** [comment]
It looks like the posters and shouts pages will work but not the resources page (I've moved it higher up in the folder, hopefully not too annoying, and added some resources, including Shouts in the shouts folder). I guess now that's on the server we can delete it from the repo, and password protect that folder?
