### ISSUE TITLE
Chicago MJ

### ISSUE THREAD

**Issue by katiesteckles** [MathsJam/mathsjam-site#26]
Note to self: Chicago is meeting on the LAST Tuesday, just until August and will then revert to normal.

**Comment by katiesteckles** [comment]
it now says 'last Tuesday' on the page, but the date isn't updated; does your Javascript thing understand 'last' or would it need to 'first-to-last', and if so can it be that without it saying that?

**Comment by christianp** [comment]
Bug in the code! And it didn't understand "last tuesday". "Fixed now.
