### ISSUE TITLE
Adding mastodon/mathstodon links?

### ISSUE THREAD

**Issue by dietercastel** [MathsJam/mathsjam-site#343]
Hi there,

Could we have a "mastodon"/"mathstodon" button/ key-value pair for the local jams? I'm guessing this would be a small change but one that should happen on the 'main' repository of the site. If I'm allowed access I could add it myself. :-) 

[Our local Leuven Jam is now on Mathstodon](https://mathstodon.xyz/@leuvenMJ)

kr,
Dieter

**Comment by christianp** [comment]
Great idea!

**Comment by christianp** [comment]
Maybe this should be abstracted: a list of name/URL pairs for any links to do with the jam, which might include twitter or mastodon.

**Comment by katiesteckles** [comment]
Didn't we already add a thing for this, so people could have Facebook page
links and such?

**Comment by christianp** [comment]
It looks like I just added a 'facebook' property along with 'twitter'. I'll abstract it out now, and update all the cities.

(procrastinate? me?)
