### ISSUE TITLE
Add a page with attribution information about the site

### ISSUE THREAD

**Issue by christianp** [MathsJam/mathsjam-site#381]
There should be a page saying who made the site, and giving credit for images.

**Comment by christianp** [comment]
@katiesteckles do you know who took the photo used in the header on the Gathering pages?

![](https://mathsjam.com/assets/images/gathering-header.jpg)

**Comment by katiesteckles** [comment]
That will be Steve Kirkby (although I don't know whose cake it was).

Katie
***@***.***
