### ISSUE TITLE
Move MathsJam to https

### ISSUE THREAD

**Issue by ByJamesBurton** [MathsJam/mathsjam-site#39]
By moving MathsJam to https gives the site a ranking increase by Google, speed increase and in the future, Chrome is going to mark every http site as non-secure.

**Comment by ByJamesBurton** [comment]
Its very bad practise to collect data over http. You should update to https immediately or if not, please remove this page www.mathsjam.com/gathering/register/.

![image](https://user-images.githubusercontent.com/24654097/27452913-61ee84a4-578c-11e7-8a3e-bc931a68bdfe.png)

(Chrome)

![image](https://user-images.githubusercontent.com/24654097/27453084-174136f8-578d-11e7-8231-e057bed343c3.png)

(Firefox)

**Comment by ByJamesBurton** [comment]
If the above is not possible then I'm willing to host the page.

**Comment by ByJamesBurton** [comment]
If the above is not possible then I'm willing to host the page on my server. The server is hosted on Google Cloud Platform, harden configuration and SSL grade is (A*). The domain name is preloaded into Google Chrome HSTS list and static and dynamic key pinning implemented.

**Comment by jtpio** [comment]
Depending on how the website is hosted, maybe use [Let's Encrypt](https://letsencrypt.org/)?

**Comment by christianp** [comment]
Katie has obtained an SSL certificate, and I've set it to redirect HTTP to HTTPS
