### ISSUE TITLE
UK Gathering archive page

### ISSUE THREAD

**Issue by mscroggs** [MathsJam/mathsjam-site#402]
This page: https://www.mathsjam.com/gathering/uk/archive/

Might look nice as a grid of pictures from events or something

**Comment by katiesteckles** [comment]
While we're at it: the page with the links to the UK and Oceania Gathering could have two pics for the links

**Comment by katiesteckles** [comment]
Here's a PR to fix the first thing: https://github.com/MathsJam/mathsjam-site/pull/411
