### ISSUE TITLE
Several talks in the gathering archives have broken links

### ISSUE THREAD

**Issue by willkirkby** [MathsJam/mathsjam-site#55]
I've just submitted a pull request (https://github.com/MathsJam/mathsjam-site/pull/54) that fixes most of these, but there are a few for which I wasn't able to determine the corrected link. Namely, these are:

Francis Hunt - Log 3 from a piano (2013)  
Karen Hancock - APs of Perfect Squares (2016)  
Dominika Vasilikova - Cardioids in Coffee Cups (2016)

**Comment by katiesteckles** [comment]
Amazing! These were all basically typos in the filenames, but I've fixed them all now. Thanks!
