### ISSUE TITLE
Inconsistencies in the programme page

### ISSUE THREAD

**Issue by Angelastic** [MathsJam/mathsjam-site#57]
The programme for the gathering says 'Full details, and pricing, will be made available once registration opens...'  while the main page says registration is open already. Also, the register link on that page goes to http://www.solipsys.co.uk/MathsJamRegister.html while the Register link on the side goes to http://www.mathsjam.com/gathering/register/

I'd fix it, but I'm just a random bystander who doesn't know which information is correct. :)

**Comment by katiesteckles** [comment]
Thanks - we've fixed the wording. There are two different ways to get to the registration page, but they both go to the same place so this is fine.

Thanks for your help!
