### ISSUE TITLE
We're massively inconsistent with countries

### ISSUE THREAD

**Issue by katiesteckles** [MathsJam/mathsjam-site#70]
In the 'rest of world' category, some but not all of the places are 'City, Country'. We should be more consistent.

**Comment by katiesteckles** [comment]
But if I put commas in them it'll fuck up the retweeter augh

**Comment by christianp** [comment]
What's this about commas?
If that's something that can't be fixed, we could easily add a `country` field.

**Comment by katiesteckles** [comment]
The CSV generated for the Twitter bot has the Jam Name in it, and if this contains a comma it makes a nonsense of the CSV. We could output the Jam Name in quotes, or just never use a comma in it.

**Comment by christianp** [comment]
I know which of those options sounds more sensible.

**Comment by katiesteckles** [comment]
Hang fire! Andrew strips out ", " so it's all gravy.
